#!/command/with-contenv sh
# This file must keep LF endings because s6 executes it inside Linux.

exec 2>&1
exec /usr/local/bin/rw-core \
    -config @"${INTERNAL_SOCKET_PATH}":/internal/get-config?token="${INTERNAL_REST_TOKEN}" \
    -format json
